### ISSUE TITLE
To-do List For Presentation

### ISSUE THREAD

**Issue by 3osmic** [3osmic/Parking-Lot-System#48]

**Comment by 3osmic** [comment]
- [ ] Youssef (Included/Excluded - Project Overview)
- [ ] Business Requirements
- [ ] Non-Functional Requirements
- [ ] Database / Classes
- [ ] Achievements and Challenges
- [ ] Future Development Plan / Q&A
- [ ] Format Presentation Slides
- [ ] Schedule mock presentation with team
